### ISSUE TITLE
Anyone having issues with assistant working? 

### ISSUE THREAD

**Issue by TJJP** [kylejramstad/garage-pi-v2#22]
I have been trying to get the assistant to work, but it never goes through with the using IFTTT. If I take the URL that IFTTT generates:  

`https://127.0.0.1/assistant?open=true&username=assistant&password=###############time=August 20, 2022 at 11:23PM` 

I take that URL and put it into my browser then it redirects me to the login page first. If I login and run the command again it will send the command. I make sure that the time is updated as well if it takes me a few minutes to copy. 

I downloaded a fresh download and built it to make sure nothing was weird. I tried it in a REST Client as well and I got the same direction to a login page. 

Is anyone else having this problem?

**Comment by kylejramstad** [comment]
I am working on this fix now. I should have an update or two out today.
The issue is being caused by a change in ifttt and in google.

After the update you'll need to setup the assistant again. You'll notice some instructions change. The url will also change a bit.

**Comment by kylejramstad** [comment]
Just found the fix. It also involved me accidentally checking for authentication when google and alexa can't do that. That's why you saw it redirecting you to the login page. So I have fixed it to work with the new IFTTT google assistant v2 and fixed the login issue.

Give me an hour or two to push out the update for the build and for the download. I'll post here when I'm done.

**Comment by kylejramstad** [comment]
Should be good to make a new build or download

Remember to stop and then remove the docker container running on the pi. These commands should do it.
`sudo docker container stop garage-pi`
`sudo docker container rm garage-pi`

And then remove the old garage-pi-v2 image from docker. These commands should do it without needing to find the image id yourself if you don't know how.
`sudo docker rmi $(docker images | grep 'garage-pi-v2')`

With the new install, you'll need to setup everything again unfortunately. The instructions for IFTTT have changed slightly and the URL needing to use has changed a bit thanks to Google updating their platform on IFTTT and thanks to IFTTT changing their "ingredients"

Let me know if you have any issues.
