### ISSUE TITLE
Android will not accept self-signed certs

### ISSUE THREAD

**Issue by kylejramstad** [kylejramstad/garage-pi-v2#3]
From Android N onwards it gets a littler harder, see this extract from https://stackoverflow.com/questions/4461360/how-to-install-trusted-ca-certificate-on-android-device:

> As of Android N, you need to add configuration to your app in order to have it trust the SSL certificates generated by Charles SSL Proxying. This means that you can only use SSL Proxying with apps that you control.
> 
> In order to configure your app to trust Charles, you need to add a Network Security Configuration File to your app. This file can override the system default, enabling your app to trust user installed CA certificates (e.g. the Charles Root Certificate). You can specify that this only applies in debug builds of your application, so that production builds use the default trust profile.

Because this is not an Android App, installing the certificate would only allow a properly configured application to use it. Since this is a website, the web browser used to access it is not programed to use this self-signed cert.

However, a user can bypass the warning page and chrome on android saves that user preference so that the warning does not keep appearing every time the user accesses the site.

**Research into using some other way to encrypt data between the user and the server.**

**Comment by kylejramstad** [comment]
Added note: We don't want to go the route of needing to use a VPN. The whole purpose of the login system is so that a user can see the status of the garage from anywhere in the world without needing to configure a VPN.

**Comment by kylejramstad** [comment]
Found that let's encrypt will allow people to use dynu.net ddns and issue certs for it
Here is a guide to have this done.
https://community.letsencrypt.org/t/failed-authorization-procedure-the-server-could-not-connect-to-the-client-to-verify-the-domain/60656/4?u=sahsanu

This needs to be included in the instructions. For setup. Also the cron job to make sure that dynu.net is updated if the ip address changes.

Consider having a mode for self-signed and a mode for using dynu.net and let's encrypt.

**Comment by kylejramstad** [comment]
I now have let's encrypt certs working on my own server. Need to update the build and download code to run the software to fetch proper certs. This also means that users will need valid domains from dynu.net. This seems to be the easiest free provider out there right now.

**Comment by VHHS-Robotics** [comment]
CertBot is now used and no longer need the use of self-signed certs

**Comment by kylejramstad** [comment]
No more need for self-signed certs (except as a placeholder in the dockerhub image) because we are now using CertBot to get real certs for a DDNS domain
