### ISSUE TITLE
New install issues on Raspbian Buster Lite

### ISSUE THREAD

**Issue by charredchar** [kylejramstad/garage-pi-v2#5]
I have a Raspberry Pi B+ with a completely blank SD Card, starting from scratch here for your project. I installed Raspbian Buster Lite, add SSH to the boot disk and login using Putty. I immediately start with running through your README but I always come across install issues.

I had something along these lines happen when trying to follow the howchoo writeup as well I could not get Docker to install and run correctly. I "fixed" it by using the Hypriot image with Docker reinstalled. This did not work for your scripts.

Tomorrow I can create a new blank image of Raspbian and paste in exactly what happens and the errors I come across. A few I have off the top of my head right now are the following while making an attempt to force it through.

`The command '/bin/sh -c mkdir /code' returned a non-zero code: 139`

`cannot exec in a stopped state: unknown`

**Comment by charredchar** [comment]
Complete fresh install.

https://pastebin.com/Vf05Ux0L

sudo docker ps returns this,

`CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                            PORTS               NAMES
e18f0876eae6        bugman000/garage-pi-v2   "docker-entrypoint.s…"   14 minutes ago      Restarting (139) 23 seconds ago                       garage-pi`

Seems to always be restarting.

**Comment by kylejramstad** [comment]
This project has only ever been tested on the Raspberry Pi 3 B+. I'm not sure if that is the underlying issue.

Also, I have not updated the dockerhub image properly until today. I have tested it all and even updated the instructions. Please check them out. There have been a lot of updates. You'll now need to have a DDNS service set up so that we can use real SSL/TLS certificates to keep things as secure as possible.

Please try to install the software again and then let me know if you are still having an issue.

**Comment by kylejramstad** [comment]
I have confirmed that this is a compatibility problem with Raspbian Buster.
I will be working on a fix for this. However, for now, the software is compatible with Raspbian Stretch.
Here is a link to instructions on how to install Stretch [https://howchoo.com/g/ndg2mtbmnmn/how-to-install-raspbian-stretch-on-the-raspberry-pi](https://howchoo.com/g/ndg2mtbmnmn/how-to-install-raspbian-stretch-on-the-raspberry-pi)

**Comment by charredchar** [comment]
I have not had a chance to test a new install because I was using that SD for a different garage project.

If I recall the last time I attempted to follow the howchoo guide using a Stretch image I came across a similar issue but I will try again when I get a free SD Card. Thanks for your effort and help!

**Comment by charredchar** [comment]
Installed the exact Raspbian linked and came across the same issue. I don't know why there would be an issue with it working on a Pi 3 B+ and not a Pi B+, every other GaragePi I attempt seems to work for me, even the original Howchoo once I get docker working. (Howchoo's Docker guide always ends in an error, some searching seems that it was something changed on Docker and Raspbian side.)

https://pastebin.com/jqxHN0Xm

I'll keep this SD Card as is for now so if there is anything you'd like me to try I can when I have the time. I should mention that I ended up with another controller and got it working which is why I wanted another SD Card to test. While this one is working I would prefer to try out yours as it seems more secure and has Assistant built in.

https://github.com/andrewshilliday/garage-door-controller

Thanks for your help and work so far!

**Comment by kylejramstad** [comment]
Can you type this into your terminal
`sudo docker logs garage-pi`

This will print out all the errors inside the docker container and might give me a reason why it keeps stopping and restarting itself.

Thank you

**Comment by charredchar** [comment]
That command returns nothing. Not an error or empty file, just nothing.

Thinking back to the difference here being using the Pi 1 over the Pi 3, the only thing that is really different is the quantity of memory, right? Could that possibly cause it to not start up? Would that not show an error in a log? Just for the hell of it:

```
pi@raspberrypi:~ $ free -h
              total        used        free      shared  buff/cache   available
Mem:           433M         75M        125M        8.5M        232M        303M
Swap:           99M          0B         99M

```

**Comment by charredchar** [comment]
Though I am interested in the actual issue with why this doesn't work on the Pi 1 B+ I actually needed another Pi for another project I am starting up... So I bought a Pi 4 B. If you don't feel like following up with this that is okay but if you need anything else please let me know and I will keep testing for you.

On that note, I also wanted to mention that I tried this with Raspbian Buster (since Stretch doesn't work with the RP4) and all seems fine. What exactly were the issues you were having with it? I'd love to help you test for capability for Buster and the RP4 if you do not have one on hand yourself to do so.
