### ISSUE TITLE
Change ports and webpage

### ISSUE THREAD

**Issue by Poochsr** [kylejramstad/garage-pi-v2#7]
Is there a way to us another port other than 80. Also how would you add additional info to web page. For example I run a camera in my garage to verify it closes correct. I would like to just to be able to add a link to the camera to view on the page. 

Thanks,
Noob - Chuck

**Comment by kylejramstad** [comment]
Changing Ports will involve changing the Download.sh and Build.sh scripts depending on how you want to install the software. This can be added as an option for users when using either of these scripts in a future release. This is a hobby project of mine so this might be a while :(

To add a link to the page, you'll need to edit the index.ejs file. This can be done before or after building the docker container (without restarting the server too). 

- Edit the index.ejs file before the build. Then build the project like normal.
- Edit the index.ejs file after the build/download
   1. SSH to the raspberry pi
   2. Open Bash on the docker container
   `sudo docker exec -it garage-pi /bin/bash`
   3. Then open the ./views/index.ejs file in your favorite text editor.
   Example: `nano ./views/index.ejs`
